apiVersion: v2
name: youless-observer
version: 0.1.0-rc2
appVersion: 0.1.0-rc2
description: Real-time usage observer service for YouLess energy meter
type: application
keywords: [youless, energy, monitor, observer, otel, mqtt]
home: https://roeldev.github.io/youless-observer
sources:
  - https://github.com/roeldev/youless-observer
maintainers:
  - name: roeldev
